import { TanStackDevtools } from '@tanstack/react-devtools'
import { type QueryClient } from '@tanstack/react-query'
import { createRootRouteWithContext, HeadContent, Scripts, useSearch } from '@tanstack/react-router'
import { TanStackRouterDevtoolsPanel } from '@tanstack/react-router-devtools'
import { type ReactNode } from 'react'

import { NotFound } from '#/components/not-found'
import { RouteError } from '#/components/route-error'
import { PostHogProvider } from '#/integrations/posthog/provider'
import { tanstackQueryDevtoolsPlugin } from '#/integrations/tanstack-query/devtools'
import { FONT_PRELOAD_LINKS } from '#/lib/font-preloads'
import { parseLanguage } from '#/lib/language'
import appCss from '#/styles.css?url'

interface RouterContext {
  queryClient: QueryClient
}

export const Route = createRootRouteWithContext<RouterContext>()({
  errorComponent: RouteError,
  head: () => ({
    meta: [
      { charSet: 'utf-8' },
      { content: 'width=device-width, initial-scale=1', name: 'viewport' },
      { title: 'Prva postava' },
    ],
    links: [
      ...FONT_PRELOAD_LINKS,
      { href: appCss, rel: 'stylesheet' },
      // Generated by `bun run generate-icons` into `public/`.
      { href: '/favicon.ico', rel: 'icon', sizes: '16x16 32x32 48x48' },
      { href: '/favicon.svg', rel: 'icon', type: 'image/svg+xml' },
      { href: '/favicon-96.png', rel: 'icon', sizes: '96x96', type: 'image/png' },
    ],
  }),
  notFoundComponent: NotFound,
  shellComponent: RootDocument,
})

interface RootDocumentProps {
  readonly children: ReactNode
}

function RootDocument({ children }: RootDocumentProps) {
  // Not every route declares `lang` (not-found does not), so read it loosely and parse it.
  const language = useSearch({ strict: false, select: (search) => parseLanguage(search.lang) })

  return (
    <html lang={language}>
      <head>
        <HeadContent />
      </head>
      <body className="[overflow-wrap:anywhere] selection:bg-tint selection:text-ink">
        <PostHogProvider>
          {children}
          <TanStackDevtools
            config={{ position: 'bottom-right' }}
            plugins={[
              { name: 'TanStack Router', render: <TanStackRouterDevtoolsPanel /> },
              tanstackQueryDevtoolsPlugin,
            ]}
          />
        </PostHogProvider>
        <Scripts />
      </body>
    </html>
  )
}
